import { ApplicantInput } from './types';

export const DEMO_APPLICANTS: { label: string; description: string; data: ApplicantInput }[] = [
  {
    label: 'Rahul Sharma — Balanced',
    description: 'Salaried, strong credit, moderate debt',
    data: {
      fullName: 'Rahul Sharma',
      age: 28,
      city: 'Pune',
      dependents: 2,
      employmentType: 'Salaried',
      monthlyIncome: 75000,
      otherMonthlyIncome: 5000,
      employmentDurationYears: 4,
      creditScore: 782,
      existingLoanBalance: 240000,
      existingMonthlyEmi: 9000,
      activeLoans: 1,
      repaymentHistory: 'Excellent',
      loanType: 'Personal Loan',
      loanAmount: 1200000,
      loanTenureYears: 5,
      interestRate: 10.5,
      monthlyExpenses: 28000,
      monthlySavings: 20000,
      otherObligations: 3000,
    },
  },
  {
    label: 'Priya Verma — Strong',
    description: 'High income, excellent credit, low debt',
    data: {
      fullName: 'Priya Verma',
      age: 34,
      city: 'Mumbai',
      dependents: 1,
      employmentType: 'Salaried',
      monthlyIncome: 180000,
      otherMonthlyIncome: 20000,
      employmentDurationYears: 8,
      creditScore: 815,
      existingLoanBalance: 150000,
      existingMonthlyEmi: 5000,
      activeLoans: 1,
      repaymentHistory: 'Excellent',
      loanType: 'Home Loan',
      loanAmount: 3500000,
      loanTenureYears: 20,
      interestRate: 8.4,
      monthlyExpenses: 45000,
      monthlySavings: 80000,
      otherObligations: 2000,
    },
  },
  {
    label: 'Amit Kumar — Medium Risk',
    description: 'Moderate credit, elevated DTI',
    data: {
      fullName: 'Amit Kumar',
      age: 31,
      city: 'Delhi',
      dependents: 3,
      employmentType: 'Self Employed',
      monthlyIncome: 95000,
      otherMonthlyIncome: 8000,
      employmentDurationYears: 3,
      creditScore: 688,
      existingLoanBalance: 580000,
      existingMonthlyEmi: 22000,
      activeLoans: 2,
      repaymentHistory: 'Good',
      loanType: 'Vehicle Loan',
      loanAmount: 800000,
      loanTenureYears: 4,
      interestRate: 11.2,
      monthlyExpenses: 35000,
      monthlySavings: 12000,
      otherObligations: 5000,
    },
  },
  {
    label: 'Suresh Patel — High Risk',
    description: 'Low credit, high debt, unstable income',
    data: {
      fullName: 'Suresh Patel',
      age: 27,
      city: 'Ahmedabad',
      dependents: 4,
      employmentType: 'Freelancer',
      monthlyIncome: 42000,
      otherMonthlyIncome: 3000,
      employmentDurationYears: 1,
      creditScore: 542,
      existingLoanBalance: 850000,
      existingMonthlyEmi: 18000,
      activeLoans: 3,
      repaymentHistory: 'Poor',
      loanType: 'Personal Loan',
      loanAmount: 600000,
      loanTenureYears: 3,
      interestRate: 14.5,
      monthlyExpenses: 22000,
      monthlySavings: 3000,
      otherObligations: 4000,
    },
  },
  {
    label: 'Neha Singh — Conditional',
    description: 'Good credit but tight affordability',
    data: {
      fullName: 'Neha Singh',
      age: 30,
      city: 'Bengaluru',
      dependents: 2,
      employmentType: 'Business Owner',
      monthlyIncome: 110000,
      otherMonthlyIncome: 10000,
      employmentDurationYears: 5,
      creditScore: 745,
      existingLoanBalance: 320000,
      existingMonthlyEmi: 14000,
      activeLoans: 1,
      repaymentHistory: 'Good',
      loanType: 'Business Loan',
      loanAmount: 1500000,
      loanTenureYears: 5,
      interestRate: 12.0,
      monthlyExpenses: 40000,
      monthlySavings: 15000,
      otherObligations: 6000,
    },
  },
];

export const EMPTY_APPLICANT: ApplicantInput = {
  fullName: '',
  age: 25,
  city: '',
  dependents: 0,
  employmentType: 'Salaried',
  monthlyIncome: 0,
  otherMonthlyIncome: 0,
  employmentDurationYears: 0,
  creditScore: 700,
  existingLoanBalance: 0,
  existingMonthlyEmi: 0,
  activeLoans: 0,
  repaymentHistory: 'Good',
  loanType: 'Personal Loan',
  loanAmount: 500000,
  loanTenureYears: 5,
  interestRate: 10.5,
  monthlyExpenses: 0,
  monthlySavings: 0,
  otherObligations: 0,
};
